_SPECIALIZATION_LIST = [
    "ginekolog",
    "ortopeda",
    "psycholog",
    "psychiatra",
    "stomatolog",
    "dermatolog",
    "chirurg",
    "laryngolog",
    "fizjoterapeuta",
    "internista",
    "neurolog",
    "okulista",
    "pediatra",
    "endokrynolog",
    "urolog",
    "kardiolog",
    "neurochirurg",
    "psychoterapeuta",
    "gastrolog",
    "radiolog",
    "alergolog",
    "lekarz rodzinny",
    "dietetyk",
    "onkolog",
    "reumatolog",
    "lekarz wykonujący zabiegi medycyny estetycznej",
    "chirurg naczyniowy",
    "pulmonolog",
    "diabetolog",
    "chirurg plastyczny",
    "ortodonta",
    "hematolog",
    "neurolog dziecięcy",
    "proktolog",
    "logopeda",
    "weterynarz",
    "lekarz medycyny pracy",
    "osteopata",
    "ortopeda dziecięcy",
    "chirurg dziecięcy",
    "psychiatra dziecięcy",
    "nefrolog",
    "chirurg szczękowo-twarzowy",
    "lekarz chorób zakaźnych",
    "anestezjolog",
    "chirurg onkologiczny",
    "seksuolog",
    "ultrasonografista",
    "laryngolog dziecięcy",
    "lekarz bez specjalizacji",
    "chirurg stomatologiczny",
    "kardiolog dziecięcy",
    "flebolog",
    "optometrysta",
    "gastrolog dziecięcy",
    "położna/położny",
    "lekarz rehabilitacji medycznej",
    "immunolog",
    "fizjoterapeuta dziecięcy",
    "endokrynolog dziecięcy",
    "angiolog",
    "psycholog dziecięcy",
    "kardiochirurg",
    "urolog dziecięcy",
    "hepatolog",
    "alergolog dziecięcy",
    "audiolog, foniatra",
    "androlog",
    "higienistka/higienista stomatologiczny",
    "pulmonolog dziecięcy",
    "okulista dziecięcy",
    "genetyk",
    "geriatra",
    "stomatolog dziecięcy",
    "hipertensjolog",
    "radioterapeuta onkologiczny",
    "diagnostyka",
    "lekarz medycyny sportowej",
    "hematolog dziecięcy",
    "patomorfolog",
    "Lekarz pierwszego kontaktu",
    "neonatolog",
    "protetyk stomatologiczny",
    "nefrolog dziecięcy",
    "perinatolog",
    "chirurg klatki piersiowej",
    "ginekolog onkologiczny",
    "bariatra",
    "ortoptysta",
    "Lekarz medycyny nuklearnej",
    "periodontolog",
    "Dermatolog dziecięcy",
    "neurochirurg dziecięcy",
    "reumatolog dziecięcy",
    "biegły sądowy",
    "psychoonkolog",
    "onkolog dziecięcy",
    "angiochirurg",
    "lekarz medycyny ratunkowej",
    "psychotraumatolog",
]
